from crewai import Task

class Tasks:
    
    def __init__(self, user_input):
        self.user_input = user_input

    def web_researcher_task(self, agent):
        return Task(
            description=(
                "Perform extensive web researcher related to "
                "the topic {} ".format(self.user_input)                            
            ),
            expected_output=(
                "Final output must be a table with one column showing website referred "
                "and another column having details and useful information extacted from the website related to {}".format(self.user_input)
            ),
            agent=agent,
        )
    
    def arxiv_researcher_task(self, agent):
        return Task(
            description=(
                "Perform extensive research on arxiv.com to extract abstract from publications related to "
                "the topic {} ".format(self.user_input)                            
            ),
            expected_output=(
                "Final output must be a table with one column showing title of the paper  "
                "another column showing abstract of the publication and "
                "one more column showing useful information like authors, year extacted from the paper related to {}".format(self.user_input)
            ),
            agent=agent,
        )
    
    def analyst_task(self, agent):
        return Task(
            description=(
                "Write a comprehensive and engaging report on {}".format(self.user_input)
            ),
            expected_output=(                            
                "A techinal writeup on {} with high quality content and engagement. "
                "Provide specific details, numbers, and facts to support your content. "
                "Add a reference sub heading that conatains two tables. "
                "One generated by Senior Web Researcher and another by Senior Arxiv Literature Reviewer".format(self.user_input)
            ),
            agent=agent,
        )